### PR TITLE
Fixes issue with execution summary. Closes #416

### LINKED ISSUE #416: [BUG]: "Unknown" items reported in the execution summary
### Description

The execution summary reports Unknown items

### Expected behaviour

No unknown items in the execution summary

### Actual behaviour

```text
# Dev Proxy execution summary

Date: 2023-12-12 13:23:17

## Requests

### GET https://api.github.com/repos/microsoft/dev-proxy/issues

#### Requests passed through

- (1) Passed through

#### Unknown

- (1) GET https://api.github.com/repos/microsoft/dev-proxy/issues

## Summary

Category|Count
--------|----:
Requests intercepted|1
Requests passed through|1
Unknown|1
```

### Steps to reproduce

- enable execution summary plugin
- start proxy
- start recording
- issue a request so that it's intercepted by proxy
- stop recording
- see Unknown items in the generated summary

### Dev Proxy Version

latest from main

### Operating system (environment)

macOS

### Shell

zsh

### Additional Info

It's caused by us intercepting responses, but not updating the execution summary plugin to ignore related messages

### PR DESCRIPTION
**Pull request by waldekmastykarz**
Fixes issue with execution summary. Closes #416

### CODE REVIEW

**Review by garrytrinder — COMMENTED** [review]
I'm still seeing unknown requests in my testing.

image

Proxy started with no args and using default `devproxyrc.json` configuration with the exception of `ExecutionSummaryPlugin` enabled.

**Comment by waldekmastykarz** [comment]
I can't reproduce your issue following the steps you described. Could you please have another look?

**Comment by garrytrinder** [comment]
Issue was on my side, confirmed that unknown requests are not shown

image

**Review by garrytrinder — APPROVED** [review]
Issue was my end, working as expected.

image

**Pull request merged**
