### PR TITLE
Fix for Dev Proxy Installation Script on Linux:  #558

### PR DESCRIPTION
**Pull request by SilentSobs**
Addressing issue https://github.com/microsoft/dev-proxy/issues/558 #558 

To correct and improve the line for version detection that wasn't working properly, and to incorporate the use of grep 
```
version=$(curl -s https://api.github.com/repos/microsoft/dev-proxy/releases/latest | grep -o '"tag_name": *"[^"]*"' | sed 's/"tag_name": *"\(.*\)"/\1/')
```
This version uses grep to filter the line that contains "tag_name":, making it easier to find the version string. 

```
# Check OS and set permissions accordingly
if [ "$(uname)" == "Darwin" ]; then
    # Set permissions for macOS
    chmod +x ./devproxy ./libe_sqlite3.dylib
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    # Set permissions for Linux
    chmod +x ./devproxy ./libe_sqlite3.so
fi
```

### CODE REVIEW

**Comment by SilentSobs** [comment]
The reason I changed this because while fixing the issue  i was having an issue with fetching version from the previous code 
```
version=$(curl -s https://api.github.com/repos/microsoft/dev-proxy/releases/latest | awk -F: '/"tag_name"/ {print $2}' | sed 's/[", ]//g')
```
But now i can check it is working But at that time it was not able to download the dev proxy from the script.

**Comment by waldekmastykarz** [comment]
> But now i can check it is working But at that time it was not able to download the dev proxy from the script.

Please do. I'll wait with merging until I hear back from you

**Comment by SilentSobs** [comment]
It's working.
image
image

**Comment by waldekmastykarz** [comment]
Is it the existing or the updated version of the download logic working?

**Comment by SilentSobs** [comment]
Updated version.

**Review by waldekmastykarz — CHANGES_REQUESTED** [review]
Works like a charm! Could you also please update the setup-beta.sh script?

**Comment by SilentSobs** [comment]
On macOS (Darwin), the sed -i command expects an argument immediately following -i. If we want to perform in-place editing without creating backup files, we need to provide an empty string as the argument, like this: sed -i ''.

However, on Linux systems, sed -i requires an argument specifying the suffix for backup files. If we want to perform in-place editing without creating backup files, we should omit the suffix altogether, like this: sed -i.

**Comment by SilentSobs** [comment]
image

image

**Comment by SilentSobs** [comment]
Once this installation script is fixed I will start working on the upgrade part which is left . I don't have mac os so it creates an issue for me to test on that environment . Is there any workaround for that so I can test the application on mac os something like a virtual environment for a developer.

**Review by waldekmastykarz — APPROVED** [review]

**Comment by waldekmastykarz** [comment]
> Once this installation script is fixed I will start working on the upgrade part which is left . I don't have mac os so it creates an issue for me to test on that environment . Is there any workaround for that so I can test the application on mac os something like a virtual environment for a developer.

You could try using a GitHub macOS agent and then use GitHub Actions to test your logic.

**Comment by waldekmastykarz** [comment]
Awesome work handling the discrepancies between OSes! Thank you!

**Pull request merged**
